module.exports = [
  { code: "auth.login", module: "auth", action: "login" },
  { code: "user.invite", module: "user", action: "invite" },
  { code: "user.view", module: "user", action: "view" },
  { code: "user.update", module: "user", action: "update" },
  { code: "user.disable", module: "user", action: "disable" },
  { code: "employee.view", module: "employee", action: "view" },
  { code: "employee.assign", module: "employee", action: "assign" },
  { code: "role.view", module: "role", action: "view" },
  { code: "role.assign", module: "role", action: "assign" },
  { code: "position.create", module: "position", action: "create" },
  { code: "position.update", module: "position", action: "update" },
  { code: "position.assign", module: "position", action: "assign" },
  { code: "workflow.submit", module: "workflow", action: "submit" },
  { code: "workflow.approve", module: "workflow", action: "approve" },
  { code: "workflow.reject", module: "workflow", action: "reject" },
  { code: "workflow.return", module: "workflow", action: "return" },
  { code: "form.create", module: "form", action: "create" },
  { code: "form.publish", module: "form", action: "publish" },
  { code: "form.view", module: "form", action: "view" },
  { code: "report.view", module: "report", action: "view" },
  { code: "audit.view", module: "audit", action: "view" },
  { code: "tenant.manage", module: "tenant", action: "manage" },
];
